/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_vpe_ctrl_GpuManage */

#ifndef _Included_org_cripac_isee_vpe_ctrl_GpuManage
#define _Included_org_cripac_isee_vpe_ctrl_GpuManage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getInfoCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getInfoCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getPid
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getPid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getUsedGpuMemory
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getUsedGpuMemory
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    initNVML
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_initNVML
  (JNIEnv *, jobject);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getDeviceCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getDeviceCount
  (JNIEnv *, jobject);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getFanSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getFanSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getUtilizationRate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getUtilizationRate
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getFreeMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getFreeMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getTotalMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getTotalMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getUsedMemory
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getUsedMemory
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getTemperature
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getTemperature
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getSlowDownTemperatureThreshold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getSlowDownTemperatureThreshold
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getShutdownTemperatureThreshold
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getShutdownTemperatureThreshold
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getPowerLimit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getPowerLimit
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_cripac_isee_vpe_ctrl_GpuManage
 * Method:    getPowerUsage
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_vpe_ctrl_GpuManage_getPowerUsage
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
