CudaMonitor4j4GpuManage.so:CudaMonitor4j4GpuManage.o
	gcc -I"${JAVA_HOME}/include" -I"${JAVA_HOME}/include/linux" -shared -o CudaMonitor4j4GpuManage.so CudaMonitor4j4GpuManage.o
CudaMonitor4j4GpuManage.o:CudaMonitor4j4GpuManage.c
	gcc -I"${JAVA_HOME}/include" -I"${JAVA_HOME}/include/linux" -c -fPIC -o CudaMonitor4j4GpuManage.o CudaMonitor4j4GpuManage.c