/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cripac_isee_alg_pedestrian_classifier_ImgClassification */

#ifndef _Included_org_cripac_isee_alg_pedestrian_classifier_ImgClassification
#define _Included_org_cripac_isee_alg_pedestrian_classifier_ImgClassification
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cripac_isee_alg_pedestrian_classifier_ImgClassification
 * Method:    loadLibrary
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_alg_pedestrian_classifier_ImgClassification_loadLibrary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_cripac_isee_alg_pedestrian_classifier_ImgClassification
 * Method:    initialize
 * Signature: (JLjava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_cripac_isee_alg_pedestrian_classifier_ImgClassification_initialize
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_cripac_isee_alg_pedestrian_classifier_ImgClassification
 * Method:    classify
 * Signature: (J[BIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_cripac_isee_alg_pedestrian_classifier_ImgClassification_classify
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     org_cripac_isee_alg_pedestrian_classifier_ImgClassification
 * Method:    release
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_cripac_isee_alg_pedestrian_classifier_ImgClassification_release
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_cripac_isee_alg_pedestrian_classifier_ImgClassification
 * Method:    closeLibrary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_cripac_isee_alg_pedestrian_classifier_ImgClassification_closeLibrary
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
